version: "3"

services:
  app:
    container_name: app
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - gcr.io/aleroxac/goexpert-weather-api:v1
    ports:
      - 8080:8080
    healthcheck:
      test: "wget -q --spider http://localhost:8080/status || exit 1"
      start_period: 5s
      timeout: 5s
      interval: 10s
      retries: 3
